services:
  db:
    container_name: twitter-db
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: my_app_user
      MYSQL_PASSWORD: your_password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - db_data:/var/lib/mysql
    - ./database/log/mysql:/var/log/mysql
    - ./database/my.conf:/etc/mysql/conf.d/my.conf
    - ./database/init:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  backend:
    container_name: twitter-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://my_app_user:your_password@db:3306/my_app_db
    ports:
      - "5001:5000" # FastAPIのデフォルトポート
    volumes:
      - ./backend:/backend

  frontend:
    container_name: twitter-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "4200:4200"  # Angularの開発サーバーポート
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  #ファイルの変更を検知

  nginx:
    container_name: twitter-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80" # ホスト側のポート8080でnginxを公開
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  # frontend_node_modules:
